name: 'Changesets'
description: 'Automate versioning and changelog management using Changesets'
inputs:
  publish:
    description: 'The command to use to build and publish packages'
    required: false
  version:
    description: 'The command to use to update versions'
    required: false
  commit:
    description: 'The message to use when committing changes'
    required: false
    default: 'Version Packages'
  title:
    description: 'The title to use for the pull request'
    required: false
    default: 'Version Packages'
runs:
  using: 'node16'
  main: 'dist/index.js'
